[tool.black]
line-length = 119
target-version = ['py38', 'py39', 'py310']

[tool.isort]
known_first_party = "autogluon"
known_third_party = [
    "gluonts",
    "mxnet",
    "networkx",
    "numpy",
    "pandas",
    "psutil",
    "pytest",
    "scipy",
    "sklearn",
    "sktime",
    "statsmodels",
    "tqdm",
    "Pillow",
    "boto3",
    "requests",
    "timm",
    "torch",
    "torchvision",
    "fairscale",
    "scikit-image",
    "smart_open",
    "lightning",
    "torchmetrics",
    "transformers",
    "nptyping",
    "omegaconf",
    "pytorch-metric-learning",
    "nlpaug",
    "nltk",
]
line_length = 119
profile = "black"


[tool.codespell]
skip = '.git,*.pdf,*.svg,*.ipynb,*.csv,kaggle_feedback_prize'
#
ignore-words-list = 'mape,ans,2st,fo,nd,te,fpr,coo,rouge,SME'


[tool.ruff]
lint.ignore = [
    "E501",  # Line too long
    "E731",  # Do not assign a `lambda` expression, use a `def`
    "E722",  # Do not use bare `except`
]
extend-exclude = ["__init__.py"]
