[tool.ruff]
line-length = 119
target-version = "py38"
extend-exclude = ["__init__.py"]
lint.ignore = [
    "E501",  # Line too long
    "E731",  # Do not assign a `lambda` expression, use a `def`
    "E722",  # Do not use bare `except`
]
lint.isort.known-first-party = ["autogluon"]
lint.isort.known-third-party = [
    "gluonts",
    "mxnet",
    "networkx",
    "numpy",
    "pandas",
    "psutil",
    "pytest",
    "scipy",
    "sklearn",
    "sktime",
    "statsmodels",
    "tqdm",
    "Pillow",
    "boto3",
    "requests",
    "timm",
    "torch",
    "torchvision",
    "fairscale",
    "scikit-image",
    "smart_open",
    "lightning",
    "torchmetrics",
    "transformers",
    "nptyping",
    "omegaconf",
    "pytorch-metric-learning",
    "nlpaug",
    "nltk",
]


[tool.codespell]
skip = '.git,*.pdf,*.svg,*.ipynb,*.csv,kaggle_feedback_prize'
#
ignore-words-list = 'mape,ans,2st,fo,nd,te,fpr,coo,rouge,SME,NoES'


[tool.pyright]
include = [
    "timeseries/src/"
]
extraPaths = [
    "common/src",
    "core/src",
    "tabular/src",
    "timeseries/src",
]