name: Build Latest Image

on:
  workflow_dispatch:
  schedule:
    - cron: "59 8 * * *"

permissions:
  id-token: write
  contents: read

jobs:
  build_cpu_training:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::369469875935:role/CloudCIECRRole
        role-duration-seconds: 3600
        aws-region: us-east-1
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true
    - name: Build the Docker image
      run: |
        chmod +x ./login_ecr.sh; ./login_ecr.sh
        docker build -f CI/docker/Dockerfile.cpu-training -t autogluon-nightly-training:cpu-latest .
        docker tag autogluon-nightly-training:cpu-latest 369469875935.dkr.ecr.us-east-1.amazonaws.com/autogluon-nightly-training:cpu-latest
        docker push 369469875935.dkr.ecr.us-east-1.amazonaws.com/autogluon-nightly-training:cpu-latest
  build_cpu_inference:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::369469875935:role/CloudCIECRRole
        role-duration-seconds: 3600
        aws-region: us-east-1
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true
    - name: Build the Docker image
      run: |
        chmod +x ./login_ecr.sh; ./login_ecr.sh
        docker build -f CI/docker/Dockerfile.cpu-inference -t autogluon-nightly-inference:cpu-latest .
        docker tag autogluon-nightly-inference:cpu-latest 369469875935.dkr.ecr.us-east-1.amazonaws.com/autogluon-nightly-inference:cpu-latest
        docker push 369469875935.dkr.ecr.us-east-1.amazonaws.com/autogluon-nightly-inference:cpu-latest
  build_gpu_training:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::369469875935:role/CloudCIECRRole
        role-duration-seconds: 3600
        aws-region: us-east-1
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true
    - name: Build the Docker image
      run: |
        chmod +x ./login_ecr.sh; ./login_ecr.sh
        docker build -f CI/docker/Dockerfile.gpu-training -t autogluon-nightly-training:gpu-latest .
        docker tag autogluon-nightly-training:gpu-latest 369469875935.dkr.ecr.us-east-1.amazonaws.com/autogluon-nightly-training:gpu-latest
        docker push 369469875935.dkr.ecr.us-east-1.amazonaws.com/autogluon-nightly-training:gpu-latest
  build_gpu_inference:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::369469875935:role/CloudCIECRRole
        role-duration-seconds: 3600
        aws-region: us-east-1
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true
    - name: Build the Docker image
      run: |
        chmod +x ./login_ecr.sh; ./login_ecr.sh
        docker build -f CI/docker/Dockerfile.gpu-inference -t autogluon-nightly-inference:gpu-latest .
        docker tag autogluon-nightly-inference:gpu-latest 369469875935.dkr.ecr.us-east-1.amazonaws.com/autogluon-nightly-inference:gpu-latest
        docker push 369469875935.dkr.ecr.us-east-1.amazonaws.com/autogluon-nightly-inference:gpu-latest
