# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# Note: the first change per day is used to build daily/night release.
# Therefore, merging one PR per day is recommended. Otherwise, the we need to manually trigger the CI later.

name: Upload Python Package

on:
  workflow_dispatch:
  schedule:
    - cron: "59 8 * * *"

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine pypandoc packaging
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets. PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets. PYPI_PASSWORD }}
        run: |
          for v in common core features tabular multimodal timeseries autogluon
          do
            cd "$v"/

            # Copy _setup_utils.py from core to each module for tar.gz inclusion
            if [ "$v" != "core" ]; then
              cp ../core/src/autogluon/core/_setup_utils.py ./_setup_utils.py
            fi

            cp ../LICENSE ./LICENSE
            cp ../NOTICE ./NOTICE
            cp ../README.md ./README.md
            cp ../CONTRIBUTING.md ./CONTRIBUTING.md
            cp ../SECURITY.md ./SECURITY.md

            python setup.py sdist bdist_wheel
            twine upload dist/* --verbose
            rm -f ./LICENSE ./NOTICE ./README.md ./CONTRIBUTING.md ./SECURITY.md

            # Clean up _setup_utils.py if it was copied
            if [ "$v" != "core" ]; then
              rm -f ./_setup_utils.py
            fi

            cd ..
          done
